version: 2
jobs:
  build:
    docker:
      - image: node:12-alpine
    steps:
      - checkout
      - run:
          name: install-dependencies
          command: yarn
      - run:
          name: test
          command: yarn test
      - run:
          name: linting
          command: yarn lint
      - run:
          name: prettier check
          command: yarn format --check
